[2025-10-08T15:09:54.196+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: Airflow_depi.print_hello scheduled__2025-10-01T01:36:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
